spring:
  datasource:
    url: jdbc:postgresql://localhost:54321/a1
    username: myuser
    password: mypassword
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none #update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    
bezkoder:
  openapi:
    dev-url: http://192.168.5.189:8092
    prod-url: https://192.168.5.189:8092

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days
logging:
  level:
    org:
      springframework:
        security=DEBUG:
server:
  port: 8092
